# Generated by Django 2.1.5 on 2019-02-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('like', models.IntegerField()),
                ('dislink', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
