# Generated by Django 2.1.5 on 2019-02-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='dish')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='restaurant')),
                ('name', models.CharField(max_length=30)),
                ('established', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('people', models.CharField(max_length=30)),
                ('website', models.URLField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('company_background', models.TextField()),
                ('services', models.TextField()),
                ('expertise', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
